### ISSUE TITLE
Add a spinning loading icon when loading leaderboard data

### ISSUE THREAD

**Issue by chris-tse** [freecodecampnorman/freecodecampnorman.github.io#17]
On the leaderboard page, it currently shows "Loading..." while waiting for leaderboard data to load. For a better user experience, we should have a loading spinner that makes it easy to indicate data is loading.

A loading icon using CSS animations would be preferred. Feel free to use spinner icons from places like https://loading.io/css/ or make your own!

**Comment by Jc7j** [comment]
I can also try this out :)

**Comment by RizkyRajitha** [comment]
may i give it a shot sir
