### ISSUE TITLE
Remove redundant link in homepage text

### ISSUE THREAD

**Issue by chris-tse** [freecodecampnorman/freecodecampnorman.github.io#18]
On the homepage, there are currently two instances of "freeCodeCamp.org" that are links and it is redundant. I would recommend removing the first one in favor of text that just says "FreeCodeCamp is a supportive group..." but feel free to suggest copy text improvements too!

**Comment by Jc7j** [comment]
I'd like to take this :)

**Comment by chris-tse** [comment]
Thank you. I just updated the format script in `package.json` so make sure your fork has that change as well, please.

**Comment by Jc7j** [comment]
No problem. Just created the PR :)
