### ISSUE TITLE
Typography Improvements

### ISSUE THREAD

**Issue by chris-tse** [freecodecampnorman/freecodecampnorman.github.io#19]
The site is currently using default styles from React-Bootstrap. We previously had some Google Fonts in there but I didn't think they were the best choices so I removed them during the Gatsby rewrite. 

I would appreciate typography improvement suggestions, preferably using free/open source fonts.

**Comment by RizkyRajitha** [comment]
sir will this work

https://fonts.google.com/specimen/Montserrat?selection.family=Montserrat

**Comment by chris-tse** [comment]
Thanks for the suggestion. We actually used Montserrat previously. It wasn't a bad choice, but I wanted to explore other options. This issue may be a bit out of scope for hacktoberfest so I will be removing the hacktoberfest label and keep this open for further discussion among local members.

**Comment by RizkyRajitha** [comment]
ok sir ,  is there something else i can help you out
